server:
  port: 8200
  devtools:
    livereload:
      port: 35739
spring:
  application:
    name: ui-driven-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/warehousedb?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1 guy 2 code
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
  client:
    servicUrl:
      defaultZone:
        http://localhost:8761/eureka
